### ISSUE TITLE
This revamped version have been reviewed through XJTU library.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Aetf/xjtuthesis#14]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.

Based on 0.6.0/0.6.2. Please merge to mainstream.
```

Original issue reported on code.google.com by `wanderhuang` on 6 Jun 2012 at 8:01

Attachments:
* [xjtuthesis.cls](https://storage.googleapis.com/google-code-attachments/xjtuthesis/issue-14/comment-0/xjtuthesis.cls)
* [GBT7714-2005NLang-UTF8.bst](https://storage.googleapis.com/google-code-attachments/xjtuthesis/issue-14/comment-0/GBT7714-2005NLang-UTF8.bst)
* [declaration.pdf](https://storage.googleapis.com/google-code-attachments/xjtuthesis/issue-14/comment-0/declaration.pdf)

**Comment by Aetf** [comment]
Moved to pull request #25
