### ISSUE TITLE
Equations are not centering by default

### ISSUE THREAD

**Issue by CosmoGao** [Aetf/xjtuthesis#29]
While testing the templete, I found that when I use the environment as that:
```LaTex
\begin{equation}
    equation
\end{equation}
```
the equation will indent for 4 bytes, but on centering.

---

Suggest that use the package amsmath without fleqn.

**Comment by Aetf** [comment]
Thanks for report!

hmm, AFAIK left indented equation was a requirement from the official word template file. There may be updates to that file, though. Could you provide the latest version of the official word template file from the school so I can update accordingly?

**Comment by CosmoGao** [comment]
Thanks for your reply!
I have graduated for years and now helping my friend to finish her paper, maybe she has provide me the former copy, and I will ask her for the latest version of the template.

Yours Sincerely!

**Comment by longlongman** [comment]
you should remove the "fleqn" in "\RequirePackage[fleqn]{amsmath}" from the "xjtuthesis.cls".

**Comment by Aetf** [comment]
@longlongman Is centered equations the requirement from the latest standard?

**Comment by wangxuchuang** [comment]
Hi Aetf, I checked the latest bachelor thesis word template. The left indentation is required.

**Comment by Aetf** [comment]
@wangxuchuang Thanks! could you provide a link to the latest template? I can then update the wiki with new template

**Comment by wangxuchuang** [comment]
@Aetf  Try this one: [http://pts.xjtu.edu.cn:8080/UpLoadFile/429099.pdf](url).

You can find requirements in page 26-32 in "撰写论文". I find the latest one -_- now requires to center equations.

**Comment by Aetf** [comment]
Also updated wiki.
