### ISSUE TITLE
Can we update some features from xjtuthesis-x into this one?

### ISSUE THREAD

**Issue by xuchuangw** [Aetf/xjtuthesis#33]
Hi, @Aetf @Tedxz 
The latest doc format undergraduate thesis can be found here:[http://pts.xjtu.edu.cn:8080/UpLoadFile/423142.doc](url)
There are 2 unpleasant problems in xjththesis' format:
1) Line space of xjtuthesis' output is far different from the doc template. 
2) There should be a half line space before table's caption. 

Zheng Xie's [https://github.com/Tedxz/xjtuthesis-x](url) has already fixed them well. How about you two merge them into xjtuthesis, too. So, our later folks can enjoy this tex template :-)

**Comment by Aetf** [comment]
Pull requests are always welcome! Maybe you can open an issue in `xjtuthesis-x` asking for upstreaming those changes here?
