### ISSUE TITLE
本科毕设格式与2021年计算机系毕设word版差距过大

### ISSUE THREAD

**Issue by wxystudio** [Aetf/xjtuthesis#37]
本人使用该模版参与2021年计算机系本科毕设答辩，全组近一半人使用该模版，均被老师要求指出行距和标题间距等格式与其他同学的word版差距过大，被要求用word排版，本人没有能力给出修正，谨以此issue提醒后来人

**Comment by Aetf** [comment]
可否给出具体哪些地方不一致？这样才有可能修改。最好能提供word版模板。

**Comment by qsdrqs** [comment]
我在毕业设计撰写过程中对模板进行了一些细节上的修改，成功通过21届软件学院答辩。已将修改整理并提交pr #38

**Comment by wxystudio** [comment]
> 我在毕业设计撰写过程中对模板进行了一些细节上的修改，成功通过21届软件学院答辩。已将修改整理并提交pr #38

兄弟你给我大早上的吓醒了。。。看了眼手机还以为学校给我把毕设打回来重写。。。

**Comment by qsdrqs** [comment]
> > 我在毕业设计撰写过程中对模板进行了一些细节上的修改，成功通过21届软件学院答辩。已将修改整理并提交pr #38
> 
> 兄弟你给我大早上的吓醒了。。。看了眼手机还以为学校给我把毕设打回来重写。。。

不会的。。毕设已经留档了

**Comment by wxystudio** [comment]
> > > 我在毕业设计撰写过程中对模板进行了一些细节上的修改，成功通过21届软件学院答辩。已将修改整理并提交pr #38
> > 
> > 
> > 兄弟你给我大早上的吓醒了。。。看了眼手机还以为学校给我把毕设打回来重写。。。
> 
> 不会的。。毕设已经留档了

因为手机提示只能看到标题 囧 
以为是教务处给我发的

**Comment by Aetf** [comment]
我把标题改得不那么夸张了 :man_facepalming:

@qsdrqs 恭喜通过答辩 你是我直系学弟hhhh 以及多谢 PR，我这两天就看

@wxystudio 现在这个 issue 没有 action item 我就先关掉了。如果你能给个 word 模板的链接 可以再打开，也许我可以看看有什么可以改进的地方。
