### ISSUE TITLE
更新一下非私有字体下载的链接

### ISSUE THREAD

**Issue by junyang-zh** [Aetf/xjtuthesis#39]
我是西交本科生，目前正在纂写毕业论文，感谢大佬的项目！
Wiki 中给出了不使用 `propfont` 选项时使用的两个字体及下载链接，现在（202305）已经失效了，我找到了新的可以访问的官方来源，维护者可考虑更新一下 Wiki。

- FreeSerif: [GNU FreeFont FTP](http://ftp.gnu.org/gnu/freefont/);
- AR Uming: [Debian package details](https://packages.debian.org/sid/fonts-arphic-uming).

文鼎悠明的官网找不到这个字体了，只有文鼎明体。Debian 用的修改项目也挂了，现在可以下载 deb 然后解压出 ttf 用。

**Comment by Aetf** [comment]
Fixed in #40
