### ISSUE TITLE
关于四级标题的设置问题

### ISSUE THREAD

**Issue by LouSQ17** [Aetf/xjtuthesis#50]
2024年的四级标题(subsubsection)需要空两个字，但是目前空了很多，是不是需要把.cls文件中的定义subsubsection部分的两个\qquad删去？我将其修改为了
\titleformat{\subsubsection}{\xiaosi}{\arabic{subsubsection})~}{0.8em}{}
\titlespacing{\subsubsection}{2em}{0.5\baselineskip}{0\baselineskip}
目前可以正常显示，与最新格式保持一致

**Comment by Aetf** [comment]
Thanks @Zipper-1!

@LouSQ17 我刚 merge 了 #48，你可以看一下问题解决了么？

**Comment by mufeng-74** [comment]
目前已经解决了，非常感谢！

**Comment by LouSQ17** [comment]
问题已经解决了，非常感谢！

> Thanks @Zipper-1!
> 
> @LouSQ17 我刚 merge 了 #48，你可以看一下问题解决了么？
